image: docker:stable

stages:
  - build image
  - run container

before_script:
  - docker info

build:
  stage: build image
  script:
    - docker build -t docker-demo-python .

deploy:
  stage: run container
  script:
    - docker run docker-demo-python
